// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: create_order.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (order_id, user_id, side, type, price, quantity, remaining_quantity, status, created_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING order_id, sequence_num, user_id, side, type, price, quantity, remaining_quantity, status, created_at
`

type CreateOrderParams struct {
	OrderID           uuid.UUID
	UserID            uuid.NullUUID
	Side              string
	Type              string
	Price             sql.NullInt64
	Quantity          int64
	RemainingQuantity int64
	Status            string
	CreatedAt         time.Time
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder,
		arg.OrderID,
		arg.UserID,
		arg.Side,
		arg.Type,
		arg.Price,
		arg.Quantity,
		arg.RemainingQuantity,
		arg.Status,
		arg.CreatedAt,
	)
	var i Order
	err := row.Scan(
		&i.OrderID,
		&i.SequenceNum,
		&i.UserID,
		&i.Side,
		&i.Type,
		&i.Price,
		&i.Quantity,
		&i.RemainingQuantity,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
