// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: create_trade.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTrade = `-- name: CreateTrade :one
INSERT INTO trades (trade_id, maker_order_id, taker_order_id, maker_user_id, taker_user_id, price, quantity, created_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
) 
RETURNING trade_id, maker_order_id, taker_order_id, maker_user_id, taker_user_id, price, quantity, trade_seq, created_at
`

type CreateTradeParams struct {
	TradeID      uuid.UUID
	MakerOrderID uuid.NullUUID
	TakerOrderID uuid.NullUUID
	MakerUserID  uuid.NullUUID
	TakerUserID  uuid.NullUUID
	Price        int64
	Quantity     int64
	CreatedAt    time.Time
}

func (q *Queries) CreateTrade(ctx context.Context, arg CreateTradeParams) (Trade, error) {
	row := q.db.QueryRowContext(ctx, createTrade,
		arg.TradeID,
		arg.MakerOrderID,
		arg.TakerOrderID,
		arg.MakerUserID,
		arg.TakerUserID,
		arg.Price,
		arg.Quantity,
		arg.CreatedAt,
	)
	var i Trade
	err := row.Scan(
		&i.TradeID,
		&i.MakerOrderID,
		&i.TakerOrderID,
		&i.MakerUserID,
		&i.TakerUserID,
		&i.Price,
		&i.Quantity,
		&i.TradeSeq,
		&i.CreatedAt,
	)
	return i, err
}
