// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_command_seq.sql

package database

import (
	"context"
)

const getCommandSeq = `-- name: GetCommandSeq :one
SELECT sequence_num FROM commands
`

func (q *Queries) GetCommandSeq(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCommandSeq)
	var sequence_num int64
	err := row.Scan(&sequence_num)
	return sequence_num, err
}
