// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_order.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getOrder = `-- name: GetOrder :one
SELECT order_id, sequence_num, user_id, side, type, price, quantity, remaining_quantity, status, created_at FROM orders
WHERE order_id = $1 LIMIT 1
`

func (q *Queries) GetOrder(ctx context.Context, orderID uuid.UUID) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrder, orderID)
	var i Order
	err := row.Scan(
		&i.OrderID,
		&i.SequenceNum,
		&i.UserID,
		&i.Side,
		&i.Type,
		&i.Price,
		&i.Quantity,
		&i.RemainingQuantity,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
