// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_sequence.sql

package database

import (
	"context"
)

const getSequence = `-- name: GetSequence :one
SELECT nextval('command_seq')
`

func (q *Queries) GetSequence(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSequence)
	var nextval int64
	err := row.Scan(&nextval)
	return nextval, err
}
