// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Command struct {
	SequenceNum int64
}

type Order struct {
	OrderID           uuid.UUID
	SequenceNum       sql.NullInt64
	UserID            uuid.UUID
	Side              string
	Type              string
	Price             sql.NullInt64
	Quantity          int64
	RemainingQuantity int64
	Status            string
	CreatedAt         time.Time
}

type Trade struct {
	TradeID      uuid.UUID
	MakerOrderID uuid.UUID
	TakerOrderID uuid.UUID
	MakerUserID  uuid.UUID
	TakerUserID  uuid.UUID
	Price        int64
	Quantity     int64
	TradeSeq     sql.NullInt64
	CreatedAt    time.Time
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	HashedPassword string
	Balance        int64
}
