// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: replay.sql

package database

import (
	"context"
)

const replay = `-- name: Replay :many
SELECT order_id, sequence_num, user_id, side, type, price, quantity, remaining_quantity, status, created_at FROM orders ORDER BY sequence_num
`

func (q *Queries) Replay(ctx context.Context) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, replay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.OrderID,
			&i.SequenceNum,
			&i.UserID,
			&i.Side,
			&i.Type,
			&i.Price,
			&i.Quantity,
			&i.RemainingQuantity,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
