// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: update_balance.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateBalance = `-- name: UpdateBalance :exec
UPDATE users
SET balance = balance + $1
WHERE id = $2
`

type UpdateBalanceParams struct {
	Balance int64
	ID      uuid.UUID
}

func (q *Queries) UpdateBalance(ctx context.Context, arg UpdateBalanceParams) error {
	_, err := q.db.ExecContext(ctx, updateBalance, arg.Balance, arg.ID)
	return err
}
