// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: update_command_seq.sql

package database

import (
	"context"
)

const updateCommandSeq = `-- name: UpdateCommandSeq :exec
UPDATE commands SET Sequence_num = $1
`

func (q *Queries) UpdateCommandSeq(ctx context.Context, sequenceNum int64) error {
	_, err := q.db.ExecContext(ctx, updateCommandSeq, sequenceNum)
	return err
}
