// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: update_order.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateOrder = `-- name: UpdateOrder :exec
UPDATE orders
SET remaining_quantity = $1, status = $2
WHERE order_id = $3
`

type UpdateOrderParams struct {
	RemainingQuantity int64
	Status            string
	OrderID           uuid.UUID
}

func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateOrder, arg.RemainingQuantity, arg.Status, arg.OrderID)
	return err
}
